trainingInput:
  scaleTier: CUSTOM
  masterType: standard_gpu
  region: europe-west1
  hyperparameters:
    goal: MAXIMIZE
    hyperparameterMetricTag: val_acc
    maxParallelTrials: 4
    maxTrials: 36
    algorithm: GRID_SEARCH
    enableTrialEarlyStopping: True
    params:
      - parameterName: lr
        type: DISCRETE
        discreteValues: [0.000001, 0.00001, 0.0001]
      - parameterName: batch_size
        type: DISCRETE
        discreteValues: [16, 128]
      - parameterName: use_weights  
        type: CATEGORICAL
        discreteValues: ["TRUE", "FALSE"]
      
        